#!/bin/bash


chmod +x ./scripts/pre-commit
chmod +x ./scripts/pre-push
chmod +x ./scripts/test
chmod +x ./scripts/coverage
chmod +x ./scripts/clean
chmod +x ./scripts/lint
chmod +x ./scripts/install
./scripts/install

./scripts/pre-commit
./scripts/pre-push

echo -e "\e[32mDevelopment environment ready!\e[0m"

