#!/bin/bash

if [[ "$(uname -s)" == "MINGW"* ]]; then
  python.exe -m pip install --upgrade pip
else
  pip install --upgrade pip
fi
echo -e "\e[33mInstalling project dependencies\e[0m"
pip install poetry
poetry install
