#!/bin/bash

read -p "Tests will run before you push changes remotely, continue ? (y/n): " choice
if [ "$choice" != "y" ]; then
    echo "pre-push hook will not be installed"
    exit 0
else
cat <<EOF >> .git/hooks/pre-push
#!/bin/bash

echo "Before pushing, did you tie your shoes right ?"
echo "Running tests.."
pytest tests --no-header --no-summary -q

if [ \$? -ne 0 ]; then
  echo "Testing failed. Push aborted."
  exit 1
else
  printf "Testing went successful!\nPushing changes.."
fi

exit 0
EOF
chmod +x .git/hooks/pre-push
printf "\e[33mpre-push hook installed!\nTests will run before you push changes\e[0m\n"
fi
