name: publish

on:
  push:
    branches:
      - main
      - xx

jobs:
  pypi:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Environment setup
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: poetry setup
        run: |
          bash scripts/ci/poetry_setup
      - name: publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m poetry config pypi-token.pypi $PYPI_TOKEN
          set -e
          python -m poetry publish --build
