name: test

on:
  push:
    branches:
      - main
      - xx
  pull_request:
    branches:
      - main
      - xx
    types:
      - opened
      - synchronize


permissions:
  contents: write

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files --verbose
      env:
        PRE_COMMIT_COLOR: always

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Setup
        run: |
            bash scripts/ci/poetry_setup

      - name: lint
        run: bash scripts/lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ["3.10", "3.11","3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Py setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: poetry setup
        run: |
         bash scripts/ci/poetry_setup

      - name: test
        run:  bash scripts/test


  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: poetry setup
        run: |
         bash scripts/ci/poetry_setup

      - name: test
        run:  bash scripts/coverage
      - run: pip install smokeshow
      - run: smokeshow upload htmlcov
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: CLI Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 80
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head.sha }}


  check:  # serves no purpose other than branch protection
    if: always()
    needs: [format, lint, test,coverage]
    runs-on: ubuntu-latest

    steps:
      - name: Did the needed jobs succeed or fail ?
        uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}
